# Configuration du plugin TagCustom Premium

# Paramètres de la base de données
database:
  type: "mysql" # Type de base de données : "sqlite" ou "mysql"
  mysql:
    host: "localhost"       # Adresse du serveur MySQL
    port: 3306              # Port du serveur MySQL
    database: "minecraft_data"        # Nom de la base de données MySQL
    username: "minecraft_user"        # Nom d'utilisateur MySQL
    password: "m9/.riE/r!0ZENKV"      # Mot de passe MySQL

# Configuration des tags
tags:
  nature: # Catégorie Nature
    forest:
      id: 1
      permission: "TagsCustom.forest"
      display: "<green>[Forest]</green>" # Couleur verte
    ocean:
      id: 2
      permission: "TagsCustom.ocean"
      display: "<blue>[Ocean]</blue>" # Couleur bleue

  elements: # Catégorie Éléments
    fire:
      id: 3
      permission: "TagsCustom.fire"
      display: "<red>[Fire]</red>" # Couleur rouge
    frost:
      id: 4
      permission: "TagsCustom.frost"
      display: "<gradient:#00FFFF:#1E90FF>[Frost]</gradient>" # Dégradé cyan à bleu
    flame:
      id: 5
      permission: "TagsCustom.flame"
      display: "<gradient:#FF4500:#FFA500>[Flame]</gradient>" # Dégradé orange à rouge

  cosmic: # Catégorie Cosmique
    galaxy:
      id: 6
      permission: "TagsCustom.galaxy"
      display: "<gradient:#4B0082:#8A2BE2:#00FFFF>[Galaxy]</gradient>" # Dégradé violet à bleu
    rainbow:
      id: 7
      permission: "TagsCustom.rainbow"
      display: "<rainbow>[Rainbow]</rainbow>" # Effet arc-en-ciel

  advanced: # Catégorie Avancée
    king:
      id: 8
      permission: "TagsCustom.king"
      display: "<gold><bold>[King]</bold></gold>" # Texte doré et en gras
    queen:
      id: 9
      permission: "TagsCustom.queen"
      display: "<gradient:#FF69B4:#FF1493>[Queen]</gradient>" # Dégradé rose vif
    thunder:
      id: 10
      permission: "TagsCustom.thunder"
      display: "<yellow><bold>[Thunder]</bold></yellow>" # Texte en gras et en jaune

  fun: # Catégorie Amusante
    meme_master:
      id: 11
      permission: "TagsCustom.meme"
      display: "<rainbow><bold>[Meme Master]</bold></rainbow>" # Texte arc-en-ciel et en gras
    potato:
      id: 12
      permission: "TagsCustom.potato"
      display: "<yellow>[Potato]</yellow>" # Simple couleur jaune

  mystical: # Catégorie Mystique
    shadow:
      id: 13
      permission: "TagsCustom.shadow"
      display: "<dark_gray><italic>[Shadow]</italic></dark_gray>" # Italique gris foncé
    light:
      id: 14
      permission: "TagsCustom.light"
      display: "<white><bold>[Light]</bold></white>" # Blanc et gras

# Configuration du menu
menu:
  title: "&6Choisissez un tag" # Titre du menu (support des couleurs avec &)
  rows: 6                     # Nombre de lignes dans le menu (minimum 1, maximum 6)
  filler: "GRAY_STAINED_GLASS_PANE" # Matériau pour remplir les cases vides
  navigation:
    previous: "<< Précédent"  # Texte du bouton précédent
    next: "Suivant >>"        # Texte du bouton suivant

# Configuration des joueurs (les entrées sont ajoutées dynamiquement par le plugin)
players:
# Exemple d'enregistrement d'un joueur :
# uuid_du_joueur:
#   activeTag: "fire"
